{% set name = "sahi" %}
{% set version = "0.11.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sahi-{{ version }}.tar.gz
  sha256: c592085493a6f68dc2d6bd449b283455aeb6130efa0c6aae242a68e6cdc381ad

build:
  number: 0
  noarch: python
  entry_points:
    - sahi=sahi.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - fire
    - pillow >=8.2.0
    - pybboxes ==0.1.6
    - py-opencv <=4.9.0.80
    - python >=3.6
    - pytorch
    - pyyaml
    - requests
    - shapely >=1.8.0
    - terminaltables
    - tqdm >=4.48.2

test:
  imports:
    - sahi
    - sahi.postprocess
  commands:
    - pip check
    - sahi --help
  requires:
    - pip

about:
  home: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcakyon
    - weiji14
